---
- hosts: all
  become: yes
  become_method: sudo
  
  tasks:
  
  - name: Install progs wget nano
    yum: 
      name: 
        - wget
        - nano
      state: present
    become: yes

  - name: Shutdown SElinux
    command: sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
    become: yes
    
  - name: Make script bitrix-env.sh executable  
    command: chmod +x /home/vagrant/provision/files/bitrix-env.sh
    become: yes